import opentype from 'opentype.js';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// Try regular font first (better opentype.js compat), fall back to variable
let font;
try {
  font = opentype.loadSync(join(root, 'public', 'fonts', 'NotoEmoji-Regular.ttf'));
  console.log('Loaded NotoEmoji-Regular.ttf');
} catch {
  font = opentype.loadSync(join(root, 'public', 'fonts', 'NotoEmoji-Variable.ttf'));
  console.log('Loaded NotoEmoji-Variable.ttf');
}

console.log(`  unitsPerEm: ${font.unitsPerEm}`);
console.log(`  numGlyphs: ${font.numGlyphs}\n`);

// All emojis used in the portfolio (chars WITHOUT variation selectors)
const emojis = [
  { chars: '\u{1F468}\u{200D}\u{1F4BB}', name: 'technologist' },
  { chars: '\u{1F4BC}', name: 'briefcase' },
  { chars: '\u{1F6E0}', name: 'tools' },
  { chars: '\u{1F680}', name: 'rocket' },
  { chars: '\u{1F4DC}', name: 'scroll' },
  { chars: '\u{1F393}', name: 'graduation' },
  { chars: '\u{1F4CD}', name: 'pin' },
  { chars: '\u{2709}', name: 'envelope' },
  { chars: '\u{1F31F}', name: 'star' },
  { chars: '\u{1F517}', name: 'link' },
  { chars: '\u{1F30D}', name: 'globe' },
  { chars: '\u{1F4C5}', name: 'calendar' },
  { chars: '\u{1F4BB}', name: 'laptop' },
  { chars: '\u{2699}', name: 'gear' },
  { chars: '\u{1F5C4}', name: 'cabinet' },
  { chars: '\u{2601}', name: 'cloud' },
  { chars: '\u{1F4CA}', name: 'chart' },
  { chars: '\u{1F9F0}', name: 'toolbox' },
  { chars: '\u{1F3DB}', name: 'building' },
  { chars: '\u{2764}', name: 'heart' },
];

const size = font.unitsPerEm;
const paths = {};

for (const { chars, name } of emojis) {
  try {
    const path = font.getPath(chars, 0, size, size);
    const d = path.toPathData(2);

    if (d && d.length > 5) {
      const bb = path.getBoundingBox();
      const pad = size * 0.03;
      const vb = [
        Math.floor(bb.x1 - pad),
        Math.floor(bb.y1 - pad),
        Math.ceil(bb.x2 - bb.x1 + pad * 2),
        Math.ceil(bb.y2 - bb.y1 + pad * 2),
      ].join(' ');

      paths[name] = { d, vb };
      console.log(`  OK  ${name} (${d.length} path chars)`);
    } else {
      console.log(`  EMPTY  ${name}`);
    }
  } catch (e) {
    console.log(`  ERROR  ${name}: ${e.message}`);
  }
}

// Also save individual SVG files for inspection
const svgDir = join(root, 'public', 'emoji');
mkdirSync(svgDir, { recursive: true });
for (const [name, { d, vb }] of Object.entries(paths)) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}" fill="white"><path d="${d}"/></svg>`;
  writeFileSync(join(svgDir, `${name}.svg`), svg);
}

// Build char-to-name mapping (all variant combinations)
const charToName = {};
for (const { chars, name } of emojis) {
  charToName[chars] = name;
  charToName[chars + '\uFE0F'] = name;
  charToName[chars + '\uFE0E'] = name;
}
// Also add common variant: 🛠️ has FE0F in the middle for some
// (most source code has the FE0F appended)

const output = `// Auto-generated by scripts/extract-emoji.mjs — DO NOT EDIT
export const emojiPaths = ${JSON.stringify(paths)};
export const emojiCharToName = ${JSON.stringify(charToName)};
`;

writeFileSync(join(root, 'src', 'emoji-data.js'), output);
console.log(`\nWrote src/emoji-data.js (${Object.keys(paths).length} paths)`);
console.log(`Wrote ${Object.keys(paths).length} SVG files to public/emoji/`);
